# Other Popular Machine Learning Methods
## A neural network with a Perceptron

In [8]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [9]:
# import perceptron
from sklearn.linear_model import Perceptron

In [10]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

# predictive features
X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [11]:
# split data, 80-20 split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [12]:
# normalize data, instantiate a standardscaler object
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [14]:
standardized_X_test[:10]
# or -> standardized_X_test[0:10,]

array([[ 8.59484782e-01, -2.19320028e-15,  1.06703906e+00,
         1.27109354e+00],
       [-1.28922717e+00,  9.87729597e-01, -1.63724461e+00,
        -1.66219924e+00],
       [-1.43247464e-01, -7.40797197e-01,  6.26806834e-01,
         8.31099619e-01],
       [ 5.72989855e-01,  7.40797197e-01,  1.19281969e+00,
         1.71108745e+00],
       [ 8.59484782e-01, -2.19320028e-15,  8.78368105e-01,
         6.84434981e-01],
       [ 8.59484782e-01, -4.93864798e-01,  3.12355245e-01,
         2.44441065e-01],
       [-1.14597971e+00, -1.23466200e+00, -6.93889839e-01,
        -3.42217490e-01],
       [ 7.16237318e-01, -2.46932399e-01,  1.23684292e-01,
        -4.88882129e-02],
       [ 1.14597971e+00, -1.23466200e+00,  1.06703906e+00,
         6.84434981e-01],
       [-1.00273225e+00,  1.23466200e+00, -1.63724461e+00,
        -1.66219924e+00]])

In [15]:
# create a perceptron
# we want to set up the model parameter so that it passes over the data a maximum of 50 times, learning rate = .15
# tolerance to be set 10^-3, random state to set the seed so you get the same results
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

# train the model
# ravel -> change a 2-dimensional array or a multi-dimensional array into a contiguous flattened array
perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [16]:
# make a prediction using the train model on the past data
y_pred = perceptron.predict(standardized_X_test)

In [17]:
# compare the model vs what the test data
print(y_test)

[2 0 2 2 2 1 1 1 2 0 0 0 0 1 0 1 2 1 0 1 2 2 1 1 1 1 1 1 2 2]


In [18]:
print(y_pred)

[2 0 2 2 2 1 1 0 2 0 0 1 0 0 0 1 2 0 0 0 2 2 1 1 1 0 0 1 2 2]


In [19]:
# check the accuracy of the model's prediction
# perceptron acts as a classifier
print(classification_report(y_test, y_pred))

# when we split our data into training and test sets, we didn't set a random seed, 
# so that x (training & test) set was randomly sampled

# when you don't set a seed, you see slightly different results on each iteration of the code

              precision    recall  f1-score   support

           0       0.50      0.86      0.63         7
           1       0.88      0.54      0.67        13
           2       1.00      1.00      1.00        10

    accuracy                           0.77        30
   macro avg       0.79      0.80      0.77        30
weighted avg       0.83      0.77      0.77        30



In [ ]:
# results of original case from the author
# if it predicted a value of 0 (index) -> not a very precise prediction
# if it predicted a value of 1 (index) -> not a compete prediction, so there's probably more values out there